### Create new Product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Gaming Laptop",
  "quantity": 10,
  "price": 1200.50
}

### Call all products
GET http://localhost:8080/api/products